import { NextRequest } from "next/server";
import { posix as pathPosix } from "node:path";
import JSZip from "jszip";
import type { CmsCollection, Project, SiteBlueprint, UserSettings } from "@/types";
import { derivePageStateFromHtml } from "@/lib/editor/structure";
import { buildSeoBaseUrl, resolveProjectPageSeo } from "@/lib/seo";
import { listCmsCollectionsForProject } from "@/lib/server/project-cms";
import {
  buildPreviewPageRuntime,
  findBoundCollection,
  publishedEntries,
  resolveProjectPagePublicPath,
} from "@/lib/server/project-page-runtime";
import { readUserSettings } from "@/lib/server/user-settings";
import { getAuthenticatedUser } from "@/lib/supabase/server";
import { buildFullPageHtml, buildProjectPageNavigationLinks } from "@/lib/utils";
import {
  AUTH_REQUIRED_001,
  handleRouteError,
  parseRequestBody,
  createAppError,
  API_REQUEST_002,
  SAVE_SERIALIZE_001,
} from "@/lib/errors";

export const runtime = "nodejs";

type PreviewRuntime = ReturnType<typeof buildPreviewPageRuntime>;

type ExportPageArtifact = {
  id: string;
  page: Project["pages"][number];
  publicPath: string;
  outputPath: string;
  html: string;
  seoOverrides: PreviewRuntime["seoOverrides"];
  cmsRuntimeConfig: PreviewRuntime["cmsRuntimeConfig"];
};

export async function POST(req: NextRequest) {
  const requestId = req.headers.get("x-request-id") ?? null;
  try {
    const user = await getAuthenticatedUser();
    if (!user) {
      throw createAppError({
        code: AUTH_REQUIRED_001,
        devMessage: "Unauthenticated request to export project",
        severity: "warn",
      });
    }

    const body = await parseRequestBody<{
      project?: Project;
      options?: Partial<UserSettings["exportDeployment"]>;
    }>(req);
    const settings = await readUserSettings(user.id);
    const project = body.project;
    const options = {
      exportFormat: body.options?.exportFormat ?? "sitezy-zip",
      includeAssets: body.options?.includeAssets ?? true,
      includeSeoFiles: body.options?.includeSeoFiles ?? true,
    } satisfies UserSettings["exportDeployment"];

    if (!project) {
      throw createAppError({
        code: API_REQUEST_002,
        devMessage: "Export request missing project",
        severity: "warn",
      });
    }

    const zip = new JSZip();
    const cmsCollections = project ? (await listCmsCollectionsForProject(project.id, user.id)).collections : [];

    const shouldIncludePackage = options.exportFormat !== "html-package";
    const shouldIncludeReadme = options.exportFormat !== "html-package";
    const shouldIncludeAssets = options.includeAssets || options.exportFormat === "full-package";

    if (shouldIncludeReadme) {
      zip.file("README.md", generateReadme(project));
    }

    if (shouldIncludePackage) {
      zip.file(
        "package.json",
        JSON.stringify(
          {
            name: project.name.toLowerCase().replace(/\s+/g, "-"),
            version: "1.0.0",
            description: project.brief?.description || `Generated by Sitezy`,
            scripts: {
              dev: "npx serve . -p 3000",
              start: "npx serve .",
            },
            devDependencies: {
              serve: "^14.2.3",
            },
          },
          null,
          2
        )
      );
    }

    // Global CSS
    const cssFolder = zip.folder("styles");
    if (project.blueprint) {
      const { colorScheme, typography } = project.blueprint;
      cssFolder?.file(
        "global.css",
        `/* Generated by Sitezy — ${project.name} */
:root {
  --primary: ${colorScheme.primary};
  --secondary: ${colorScheme.secondary};
  --accent: ${colorScheme.accent};
  --bg: ${colorScheme.bg};
  --text: ${colorScheme.text};
  --muted: ${colorScheme.muted || "#6b7280"};
  --border: ${colorScheme.border || "#e5e7eb"};
}

*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
html { scroll-behavior: smooth; }
body {
  font-family: '${typography.bodyFont}', system-ui, sans-serif;
  background: var(--bg);
  color: var(--text);
  line-height: 1.6;
}
h1, h2, h3, h4, h5, h6 {
  font-family: '${typography.headingFont}', system-ui, sans-serif;
  line-height: 1.2;
}
a { color: var(--primary); text-decoration: none; }
img { max-width: 100%; height: auto; }
`
      );
    }

    const normalizedPages = project.pages.map((page) => {
      const derived = derivePageStateFromHtml(page.html, page.sections);
      return {
        ...page,
        html: derived.html,
        sections: derived.sections,
      };
    });
    const exportProject = {
      ...project,
      pages: normalizedPages,
    };
    const artifacts = buildExportArtifacts(exportProject, cmsCollections);
    const artifactMap = new Map<string, ExportPageArtifact>();
    const artifactByPageId = new Map<string, ExportPageArtifact>();
    for (const artifact of artifacts) {
      artifactMap.set(artifact.publicPath, artifact);
      if (!artifactByPageId.has(artifact.page.id)) {
        artifactByPageId.set(artifact.page.id, artifact);
      }
    }

    for (const artifact of artifacts) {
      const exportedHtml = rewriteExportInternalLinks(artifact.html, artifact, artifactMap);
      const cmsRuntimeConfig = rewriteExportCmsRuntimeConfig(
        artifact.cmsRuntimeConfig,
        artifact.outputPath
      );
      const navigationLinks = buildProjectPageNavigationLinks(exportProject.pages, (target) => {
        const targetArtifact = artifactByPageId.get(target.id);
        return targetArtifact
          ? relativeHrefForOutputPaths(artifact.outputPath, targetArtifact.outputPath)
          : "";
      });
      const fullHtml = buildFullPageHtml(
        exportedHtml,
        (project.blueprint ?? null) as SiteBlueprint | null,
        artifact.page.name,
        "",
        "",
        resolveProjectPageSeo(exportProject, artifact.page, null, artifact.seoOverrides),
        {
          mode: "disabled",
          projectId: null,
          contactCaptureEnabled: false,
          newsletterCaptureEnabled: false,
          submitEndpoint: "/api/leads/submit",
        },
        {
          projectId: null,
          endpoint: null,
          enableSitezyAnalytics: false,
          ga4MeasurementId:
            settings.integrations.analytics.ga4.enabled
              ? settings.integrations.analytics.ga4.measurementId
              : null,
          metaPixelId:
            settings.integrations.analytics.metaPixel.enabled
              ? settings.integrations.analytics.metaPixel.pixelId
              : null,
        },
        cmsRuntimeConfig,
        navigationLinks,
      );
      zip.file(artifact.outputPath, fullHtml);
    }

    if (shouldIncludeAssets) {
      const assetsFolder = zip.folder("assets");
      assetsFolder?.file(
        ".gitkeep",
        "# Place your images, fonts, and other assets here\n"
      );
    }

    if (options.includeSeoFiles) {
      zip.file("robots.txt", buildRobotsTxt(project));
      zip.file("sitemap.xml", buildSitemap(project, artifacts));
    }

    // Blueprint JSON for reference
    if (project.blueprint) {
      zip.file(
        "sitezy-blueprint.json",
        JSON.stringify({ blueprint: project.blueprint, brief: project.brief }, null, 2)
      );
    }

    const zipBase64 = await zip.generateAsync({
      type: "base64",
      compression: "DEFLATE",
      compressionOptions: { level: 6 },
    });

    // Decode base64 → binary → Blob (avoids Buffer/Uint8Array BodyInit type issues)
    const binary = Buffer.from(zipBase64, "base64");
    const zipBlob = new Blob([binary], { type: "application/zip" });

    const filename = `${project.name.replace(/[^a-z0-9]/gi, "-").toLowerCase()}-sitezy.zip`;

    return new Response(zipBlob, {
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${filename}"`,
        "Content-Length": binary.byteLength.toString(),
      },
    });
  } catch (err) {
    return handleRouteError(err, requestId, SAVE_SERIALIZE_001);
  }
}

function generateReadme(project: Project): string {
  const pages = project.pages.map((p) => `- **${p.name}**: ${p.purpose || "—"}`).join("\n");
  const bp = project.blueprint;

  return `# ${project.name}

> ${bp?.tagline || project.brief?.description || ""}

Generated by **Sitezy** — AI Website Builder  
Created: ${new Date(project.createdAt).toLocaleDateString()}

## Pages

${pages}

## Design System

- **Layout Style**: ${bp?.layoutStyle || "—"}
- **Primary Color**: ${bp?.colorScheme?.primary || "—"}
- **Heading Font**: ${bp?.typography?.headingFont || "—"}
- **Body Font**: ${bp?.typography?.bodyFont || "—"}

## Getting Started

\`\`\`bash
npm install
npm run dev
# Open http://localhost:3000
\`\`\`

Or simply open \`index.html\` directly in your browser.

## Lead Capture

- Contact forms and newsletter signup in this export are static.
- Sitezy-managed lead capture only works when the project is published on Sitezy.
- If you need submissions stored and emailed to you, publish the project instead of relying on the ZIP alone.

## File Structure

\`\`\`
├── index.html          # Home page
├── pages/              # All other pages
│   └── *.html
├── styles/
│   └── global.css      # CSS variables and base styles
├── assets/             # Place images and other assets here
└── sitezy-blueprint.json  # Design blueprint reference
\`\`\`

---

*Built with [Sitezy](https://sitezy.app)*
`;
}

function normalizePublicPath(pathname: string): string {
  const trimmed = String(pathname || "/").trim();
  if (!trimmed) return "/";
  const base = trimmed.split("#")[0]?.split("?")[0] ?? trimmed;
  const withLeadingSlash = base.startsWith("/") ? base : `/${base}`;
  const withoutTrailingSlash =
    withLeadingSlash.length > 1 ? withLeadingSlash.replace(/\/+$/, "") : withLeadingSlash;
  if (
    withoutTrailingSlash === "/home" ||
    withoutTrailingSlash === "/index" ||
    withoutTrailingSlash === "/index.html"
  ) {
    return "/";
  }
  if (withoutTrailingSlash !== "/" && withoutTrailingSlash.endsWith(".html")) {
    return withoutTrailingSlash.slice(0, -5) || "/";
  }
  return withoutTrailingSlash || "/";
}

function outputPathForPublicPath(publicPath: string, options?: { forceDirectoryIndex?: boolean }) {
  const normalized = normalizePublicPath(publicPath);
  if (normalized === "/") return "index.html";
  const segments = normalized.slice(1).split("/").filter(Boolean);
  if (!segments.length) return "index.html";
  if (options?.forceDirectoryIndex || segments.length > 1) {
    return pathPosix.join("pages", ...segments, "index.html");
  }
  return pathPosix.join("pages", `${segments[0]}.html`);
}

function buildCmsDetailPublicPath(basePublicPath: string, entrySlug: string) {
  const normalizedBase = normalizePublicPath(basePublicPath);
  const safeEntrySlug = String(entrySlug || "").replace(/^\/+|\/+$/g, "");
  if (!safeEntrySlug) return normalizedBase;
  return `${normalizedBase === "/" ? "" : normalizedBase}/${safeEntrySlug}`;
}

function buildExportArtifacts(project: Project, cmsCollections: CmsCollection[]): ExportPageArtifact[] {
  const artifacts: ExportPageArtifact[] = [];

  for (const page of project.pages) {
    if (!page.html) continue;

    if (page.meta?.pageKind === "cms_detail") {
      const collection = findBoundCollection(page, cmsCollections);
      if (!collection) continue;
      const basePublicPath = resolveProjectPagePublicPath(project, page, cmsCollections);
      for (const entry of publishedEntries(collection)) {
        const previewRuntime = buildPreviewPageRuntime(project, page, cmsCollections, entry.slug);
        const publicPath = buildCmsDetailPublicPath(basePublicPath, entry.slug);
        artifacts.push({
          id: `${page.id}:${entry.id}`,
          page,
          publicPath: normalizePublicPath(publicPath),
          outputPath: outputPathForPublicPath(publicPath, { forceDirectoryIndex: true }),
          html: page.html,
          seoOverrides: previewRuntime.seoOverrides,
          cmsRuntimeConfig: previewRuntime.cmsRuntimeConfig,
        });
      }
      continue;
    }

    const previewRuntime = buildPreviewPageRuntime(project, page, cmsCollections);
    const publicPath = resolveProjectPagePublicPath(project, page, cmsCollections);
    artifacts.push({
      id: page.id,
      page,
      publicPath: normalizePublicPath(publicPath),
      outputPath: outputPathForPublicPath(publicPath),
      html: page.html,
      seoOverrides: previewRuntime.seoOverrides,
      cmsRuntimeConfig: previewRuntime.cmsRuntimeConfig,
    });
  }

  return artifacts;
}

function relativeHrefForOutputPaths(currentOutputPath: string, targetOutputPath: string) {
  const fromDir = pathPosix.dirname(currentOutputPath);
  return pathPosix.relative(fromDir, targetOutputPath) || pathPosix.basename(targetOutputPath);
}

function resolveExportArtifactHref(
  rawHref: string,
  currentArtifact: ExportPageArtifact,
  artifacts: Map<string, ExportPageArtifact>
) {
  const trimmed = rawHref.trim();
  if (
    !trimmed ||
    trimmed.startsWith("#") ||
    trimmed.startsWith("mailto:") ||
    trimmed.startsWith("tel:") ||
    trimmed.startsWith("javascript:")
  ) {
    return null;
  }

  const candidates = new Set<string>();
  const addCandidate = (candidate: string | null | undefined) => {
    if (!candidate) return;
    const normalized = normalizePublicPath(candidate);
    candidates.add(normalized);
  };

  if (/^https?:\/\//i.test(trimmed)) {
    try {
      addCandidate(new URL(trimmed).pathname || "/");
    } catch {
      return null;
    }
  } else if (trimmed.startsWith("/")) {
    addCandidate(trimmed);
  } else {
    addCandidate(`/${trimmed.replace(/^\.?\/*/, "")}`);
    try {
      addCandidate(
        new URL(trimmed, `https://sitezy.local${currentArtifact.publicPath === "/" ? "/" : `${currentArtifact.publicPath}/`}`)
          .pathname
      );
    } catch {}
  }

  for (const candidate of candidates) {
    const match = artifacts.get(candidate);
    if (match) return match;
  }

  return null;
}

function rewriteExportInternalLinks(
  html: string,
  currentArtifact: ExportPageArtifact,
  artifacts: Map<string, ExportPageArtifact>
): string {
  const rewriteHref = (rawHref: string): string => {
    const targetArtifact = resolveExportArtifactHref(rawHref, currentArtifact, artifacts);
    return targetArtifact
      ? relativeHrefForOutputPaths(currentArtifact.outputPath, targetArtifact.outputPath)
      : rawHref;
  };

  let next = html.replace(
    /\b(href|data-href)=("([^"]*)"|'([^']*)')/gi,
    (match, attr: string, quoted: string, dbl: string | undefined, sgl: string | undefined) => {
      const raw = dbl ?? sgl ?? "";
      const rewritten = rewriteHref(raw);
      const quote = quoted.startsWith("'") ? "'" : '"';
      return `${attr}=${quote}${rewritten}${quote}`;
    }
  );

  next = next.replace(
    /(location(?:\.href)?|window\.location(?:\.href)?)(\s*=\s*|\.assign\()\s*(['"])([^'"]+)\3/gi,
    (match, target: string, operator: string, quote: string, rawHref: string) => {
      const rewritten = rewriteHref(rawHref);
      return `${target}${operator}${quote}${rewritten}${quote}`;
    }
  );

  return next;
}

function rewriteExportCmsRuntimeConfig(
  config: PreviewRuntime["cmsRuntimeConfig"],
  currentOutputPath: string
): PreviewRuntime["cmsRuntimeConfig"] {
  if (!config) return null;
  if (!config.detailPathTemplate || !config.detailPathTemplate.includes(":slug")) {
    return config;
  }

  const placeholder = "__SITEZY_ENTRY_SLUG__";
  const templatePublicPath = config.detailPathTemplate.replace(":slug", placeholder);
  const templateOutputPath = outputPathForPublicPath(templatePublicPath, { forceDirectoryIndex: true });
  const relativeTemplate = relativeHrefForOutputPaths(currentOutputPath, templateOutputPath).replace(
    placeholder,
    ":slug"
  );

  return {
    ...config,
    detailPathTemplate: relativeTemplate,
  };
}

function buildRobotsTxt(project: Project) {
  const disallow = project.seo?.noindex ? "Disallow: /" : "Allow: /";
  return `User-agent: *
${disallow}

Sitemap: /sitemap.xml
`;
}

function buildSitemap(project: Project, artifacts: ExportPageArtifact[]) {
  const base = buildSeoBaseUrl(project);
  const urls = artifacts.map((artifact) => {
    const seo = resolveProjectPageSeo(project, artifact.page, null, artifact.seoOverrides);
    const fallbackUrl = artifact.publicPath === "/" ? base : `${base}${artifact.publicPath}`;
    return `  <url><loc>${seo.canonicalUrl || fallbackUrl}</loc></url>`;
  });

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.join("\n")}
</urlset>`;
}
