import { NextRequest, NextResponse } from "next/server";
import JSZip from "jszip";
import type { Project, SiteBlueprint, UserSettings } from "@/types";
import { derivePageStateFromHtml } from "@/lib/editor/structure";
import { buildSeoBaseUrl, resolveProjectPageSeo } from "@/lib/seo";
import { getAuthenticatedUser } from "@/lib/supabase/server";
import { buildFullPageHtml } from "@/lib/utils";
import {
  AUTH_REQUIRED_001,
  handleRouteError,
  parseRequestBody,
  createAppError,
  API_REQUEST_002,
  SAVE_SERIALIZE_001,
} from "@/lib/errors";

export const runtime = "nodejs";

export async function POST(req: NextRequest) {
  const requestId = req.headers.get("x-request-id") ?? null;
  try {
    const user = await getAuthenticatedUser();
    if (!user) {
      throw createAppError({
        code: AUTH_REQUIRED_001,
        devMessage: "Unauthenticated request to export project",
        severity: "warn",
      });
    }

    const body = await parseRequestBody<{
      project?: Project;
      options?: Partial<UserSettings["exportDeployment"]>;
    }>(req);
    const project = body.project;
    const options = {
      exportFormat: body.options?.exportFormat ?? "sitezy-zip",
      includeAssets: body.options?.includeAssets ?? true,
      includeSeoFiles: body.options?.includeSeoFiles ?? true,
    } satisfies UserSettings["exportDeployment"];

    if (!project) {
      throw createAppError({
        code: API_REQUEST_002,
        devMessage: "Export request missing project",
        severity: "warn",
      });
    }

    const zip = new JSZip();

    const shouldIncludePackage = options.exportFormat !== "html-package";
    const shouldIncludeReadme = options.exportFormat !== "html-package";
    const shouldIncludeAssets = options.includeAssets || options.exportFormat === "full-package";

    if (shouldIncludeReadme) {
      zip.file("README.md", generateReadme(project));
    }

    if (shouldIncludePackage) {
      zip.file(
        "package.json",
        JSON.stringify(
          {
            name: project.name.toLowerCase().replace(/\s+/g, "-"),
            version: "1.0.0",
            description: project.brief?.description || `Generated by Sitezy`,
            scripts: {
              dev: "npx serve . -p 3000",
              start: "npx serve .",
            },
            devDependencies: {
              serve: "^14.2.3",
            },
          },
          null,
          2
        )
      );
    }

    // Global CSS
    const cssFolder = zip.folder("styles");
    if (project.blueprint) {
      const { colorScheme, typography } = project.blueprint;
      cssFolder?.file(
        "global.css",
        `/* Generated by Sitezy — ${project.name} */
:root {
  --primary: ${colorScheme.primary};
  --secondary: ${colorScheme.secondary};
  --accent: ${colorScheme.accent};
  --bg: ${colorScheme.bg};
  --text: ${colorScheme.text};
  --muted: ${colorScheme.muted || "#6b7280"};
  --border: ${colorScheme.border || "#e5e7eb"};
}

*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
html { scroll-behavior: smooth; }
body {
  font-family: '${typography.bodyFont}', system-ui, sans-serif;
  background: var(--bg);
  color: var(--text);
  line-height: 1.6;
}
h1, h2, h3, h4, h5, h6 {
  font-family: '${typography.headingFont}', system-ui, sans-serif;
  line-height: 1.2;
}
a { color: var(--primary); text-decoration: none; }
img { max-width: 100%; height: auto; }
`
      );
    }

    // Pages
    const pagesFolder = zip.folder("pages");
    const normalizedPages = project.pages.map((page) => {
      const derived = derivePageStateFromHtml(page.html, page.sections);
      return {
        ...page,
        html: derived.html,
        sections: derived.sections,
      };
    });

    normalizedPages.forEach((page) => {
      if (!page.html) return;
      const slug = page.slug || page.name.toLowerCase().replace(/\s+/g, "-");
      const exportedHtml = rewriteExportInternalLinks(page.html, normalizedPages, slug);
      const fullHtml = buildFullPageHtml(
        exportedHtml,
        (project.blueprint ?? null) as SiteBlueprint | null,
        page.name,
        "",
        "",
        resolveProjectPageSeo(project, page)
      );
      const filename = slug === "home" ? "index.html" : `${slug}.html`;
      // Home goes in root, others in pages/
      if (slug === "home" || page.name.toLowerCase() === "home") {
        zip.file("index.html", fullHtml);
      } else {
        pagesFolder?.file(`${slug}.html`, fullHtml);
      }
    });

    if (shouldIncludeAssets) {
      const assetsFolder = zip.folder("assets");
      assetsFolder?.file(
        ".gitkeep",
        "# Place your images, fonts, and other assets here\n"
      );
    }

    if (options.includeSeoFiles) {
      zip.file("robots.txt", buildRobotsTxt(project));
      zip.file("sitemap.xml", buildSitemap(project, normalizedPages));
    }

    // Blueprint JSON for reference
    if (project.blueprint) {
      zip.file(
        "sitezy-blueprint.json",
        JSON.stringify({ blueprint: project.blueprint, brief: project.brief }, null, 2)
      );
    }

    const zipBase64 = await zip.generateAsync({
      type: "base64",
      compression: "DEFLATE",
      compressionOptions: { level: 6 },
    });

    // Decode base64 → binary → Blob (avoids Buffer/Uint8Array BodyInit type issues)
    const binary = Buffer.from(zipBase64, "base64");
    const zipBlob = new Blob([binary], { type: "application/zip" });

    const filename = `${project.name.replace(/[^a-z0-9]/gi, "-").toLowerCase()}-sitezy.zip`;

    return new Response(zipBlob, {
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${filename}"`,
        "Content-Length": binary.byteLength.toString(),
      },
    });
  } catch (err) {
    return handleRouteError(err, requestId, SAVE_SERIALIZE_001);
  }
}

function generateReadme(project: Project): string {
  const pages = project.pages.map((p) => `- **${p.name}**: ${p.purpose || "—"}`).join("\n");
  const bp = project.blueprint;

  return `# ${project.name}

> ${bp?.tagline || project.brief?.description || ""}

Generated by **Sitezy** — AI Website Builder  
Created: ${new Date(project.createdAt).toLocaleDateString()}

## Pages

${pages}

## Design System

- **Layout Style**: ${bp?.layoutStyle || "—"}
- **Primary Color**: ${bp?.colorScheme?.primary || "—"}
- **Heading Font**: ${bp?.typography?.headingFont || "—"}
- **Body Font**: ${bp?.typography?.bodyFont || "—"}

## Getting Started

\`\`\`bash
npm install
npm run dev
# Open http://localhost:3000
\`\`\`

Or simply open \`index.html\` directly in your browser.

## File Structure

\`\`\`
├── index.html          # Home page
├── pages/              # All other pages
│   └── *.html
├── styles/
│   └── global.css      # CSS variables and base styles
├── assets/             # Place images and other assets here
└── sitezy-blueprint.json  # Design blueprint reference
\`\`\`

---

*Built with [Sitezy](https://sitezy.app)*
`;
}

function pageSlug(page: Project["pages"][number]): string {
  return (page.slug || page.name.toLowerCase().replace(/\s+/g, "-")).replace(/^\/+|\/+$/g, "") || "home";
}

function isHomeSlug(slug: string): boolean {
  return slug === "" || slug === "home" || slug === "index";
}

function resolveProjectPageSlug(rawHref: string, pages: Project["pages"]): string | null {
  const trimmed = rawHref.trim();
  if (!trimmed) return null;
  if (
    trimmed.startsWith("#") ||
    trimmed.startsWith("mailto:") ||
    trimmed.startsWith("tel:") ||
    trimmed.startsWith("javascript:")
  ) return null;

  let candidate = trimmed;
  if (/^https?:\/\//i.test(trimmed)) {
    try {
      const url = new URL(trimmed);
      candidate = url.pathname || "/";
    } catch {
      return null;
    }
  }

  candidate = candidate.split("#")[0]?.split("?")[0] ?? candidate;
  if (!candidate) return null;

  if (candidate.startsWith("/")) {
    candidate = candidate.replace(/^\/+|\/+$/g, "") || "home";
  } else {
    candidate = candidate.replace(/^\.?\/*/, "").replace(/\/+$/g, "") || "home";
  }

  const match = pages.find((page) => pageSlug(page) === candidate || (candidate === "" && isHomeSlug(pageSlug(page))));
  return match ? pageSlug(match) : null;
}

function exportHrefForSlug(currentSlug: string, targetSlug: string): string {
  const fromHome = isHomeSlug(currentSlug);
  const toHome = isHomeSlug(targetSlug);

  if (fromHome) {
    return toHome ? "index.html" : `pages/${targetSlug}.html`;
  }
  return toHome ? "../index.html" : `${targetSlug}.html`;
}

function rewriteExportInternalLinks(html: string, pages: Project["pages"], currentSlug: string): string {
  const rewriteHref = (rawHref: string): string => {
    const targetSlug = resolveProjectPageSlug(rawHref, pages);
    return targetSlug ? exportHrefForSlug(currentSlug, targetSlug) : rawHref;
  };

  let next = html.replace(
    /\b(href|data-href)=("([^"]*)"|'([^']*)')/gi,
    (match, attr: string, quoted: string, dbl: string | undefined, sgl: string | undefined) => {
      const raw = dbl ?? sgl ?? "";
      const rewritten = rewriteHref(raw);
      const quote = quoted.startsWith("'") ? "'" : '"';
      return `${attr}=${quote}${rewritten}${quote}`;
    }
  );

  next = next.replace(
    /(location(?:\.href)?|window\.location(?:\.href)?)(\s*=\s*|\.assign\()\s*(['"])([^'"]+)\3/gi,
    (match, target: string, operator: string, quote: string, rawHref: string) => {
      const rewritten = rewriteHref(rawHref);
      return `${target}${operator}${quote}${rewritten}${quote}`;
    }
  );

  return next;
}

function buildRobotsTxt(project: Project) {
  const disallow = project.seo?.noindex ? "Disallow: /" : "Allow: /";
  return `User-agent: *
${disallow}

Sitemap: /sitemap.xml
`;
}

function buildSitemap(project: Project, pages: Project["pages"]) {
  const base = buildSeoBaseUrl(project);

  const urls = pages.map((page) => {
    const seo = resolveProjectPageSeo(project, page);
    return `  <url><loc>${seo.canonicalUrl || base}</loc></url>`;
  });

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.join("\n")}
</urlset>`;
}
