import { NextRequest, NextResponse } from "next/server";
import JSZip from "jszip";
import type { Project } from "@/types";
import { buildFullPageHtml } from "@/lib/utils";
import {
  handleRouteError,
  parseRequestBody,
  createAppError,
  API_REQUEST_002,
  SAVE_SERIALIZE_001,
} from "@/lib/errors";

export const runtime = "nodejs";

export async function POST(req: NextRequest) {
  const requestId = req.headers.get("x-request-id") ?? null;
  try {
    const body = await parseRequestBody<{ project?: Project }>(req);
    const project = body.project;

    if (!project) {
      throw createAppError({
        code: API_REQUEST_002,
        devMessage: "Export request missing project",
        severity: "warn",
      });
    }

    const zip = new JSZip();

    // README
    zip.file("README.md", generateReadme(project));

    // package.json
    zip.file(
      "package.json",
      JSON.stringify(
        {
          name: project.name.toLowerCase().replace(/\s+/g, "-"),
          version: "1.0.0",
          description: project.brief?.description || `Generated by Sitezy`,
          scripts: {
            dev: "npx serve . -p 3000",
            start: "npx serve .",
          },
          devDependencies: {
            serve: "^14.2.3",
          },
        },
        null,
        2
      )
    );

    // Global CSS
    const cssFolder = zip.folder("styles");
    if (project.blueprint) {
      const { colorScheme, typography } = project.blueprint;
      cssFolder?.file(
        "global.css",
        `/* Generated by Sitezy — ${project.name} */
:root {
  --primary: ${colorScheme.primary};
  --secondary: ${colorScheme.secondary};
  --accent: ${colorScheme.accent};
  --bg: ${colorScheme.bg};
  --text: ${colorScheme.text};
  --muted: ${colorScheme.muted || "#6b7280"};
  --border: ${colorScheme.border || "#e5e7eb"};
}

*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
html { scroll-behavior: smooth; }
body {
  font-family: '${typography.bodyFont}', system-ui, sans-serif;
  background: var(--bg);
  color: var(--text);
  line-height: 1.6;
}
h1, h2, h3, h4, h5, h6 {
  font-family: '${typography.headingFont}', system-ui, sans-serif;
  line-height: 1.2;
}
a { color: var(--primary); text-decoration: none; }
img { max-width: 100%; height: auto; }
`
      );
    }

    // Pages
    const pagesFolder = zip.folder("pages");
    project.pages.forEach((page) => {
      if (!page.html) return;
      const slug = page.slug || page.name.toLowerCase().replace(/\s+/g, "-");
      const fullHtml = buildFullPageHtml(page.html, project.blueprint, page.name);
      const filename = slug === "home" ? "index.html" : `${slug}.html`;
      // Home goes in root, others in pages/
      if (slug === "home" || page.name.toLowerCase() === "home") {
        zip.file("index.html", fullHtml);
      } else {
        pagesFolder?.file(`${slug}.html`, fullHtml);
      }
    });

    // Assets placeholder
    const assetsFolder = zip.folder("assets");
    assetsFolder?.file(
      ".gitkeep",
      "# Place your images, fonts, and other assets here\n"
    );

    // Blueprint JSON for reference
    if (project.blueprint) {
      zip.file(
        "sitezy-blueprint.json",
        JSON.stringify({ blueprint: project.blueprint, brief: project.brief }, null, 2)
      );
    }

    const zipBase64 = await zip.generateAsync({
      type: "base64",
      compression: "DEFLATE",
      compressionOptions: { level: 6 },
    });

    // Decode base64 → binary → Blob (avoids Buffer/Uint8Array BodyInit type issues)
    const binary = Buffer.from(zipBase64, "base64");
    const zipBlob = new Blob([binary], { type: "application/zip" });

    const filename = `${project.name.replace(/[^a-z0-9]/gi, "-").toLowerCase()}-sitezy.zip`;

    return new Response(zipBlob, {
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${filename}"`,
        "Content-Length": binary.byteLength.toString(),
      },
    });
  } catch (err) {
    return handleRouteError(err, requestId, SAVE_SERIALIZE_001);
  }
}

function generateReadme(project: Project): string {
  const pages = project.pages.map((p) => `- **${p.name}**: ${p.purpose || "—"}`).join("\n");
  const bp = project.blueprint;

  return `# ${project.name}

> ${bp?.tagline || project.brief?.description || ""}

Generated by **Sitezy** — AI Website Builder  
Created: ${new Date(project.createdAt).toLocaleDateString()}

## Pages

${pages}

## Design System

- **Layout Style**: ${bp?.layoutStyle || "—"}
- **Primary Color**: ${bp?.colorScheme?.primary || "—"}
- **Heading Font**: ${bp?.typography?.headingFont || "—"}
- **Body Font**: ${bp?.typography?.bodyFont || "—"}

## Getting Started

\`\`\`bash
npm install
npm run dev
# Open http://localhost:3000
\`\`\`

Or simply open \`index.html\` directly in your browser.

## File Structure

\`\`\`
├── index.html          # Home page
├── pages/              # All other pages
│   └── *.html
├── styles/
│   └── global.css      # CSS variables and base styles
├── assets/             # Place images and other assets here
└── sitezy-blueprint.json  # Design blueprint reference
\`\`\`

---

*Built with [Sitezy](https://sitezy.app)*
`;
}
