import type { Project } from "@/types";
import { uid } from "@/lib/utils";

interface DesignTokens {
  primary: string;
  secondary: string;
  accent: string;
  bg: string;
  text: string;
  muted: string;
  border: string;
  sectionPadding: string;
  containerWidth: string;
  radius: string;
  buttonRadius: string;
  shadow: string;
  softBg: string;
  strongBg: string;
  headingFont: string;
  bodyFont: string;
}

function hexToRgb(hex: string): string {
  const clean = hex.replace("#", "");
  if (clean.length !== 6) return "124, 58, 237";
  const value = Number.parseInt(clean, 16);
  return `${(value >> 16) & 255}, ${(value >> 8) & 255}, ${value & 255}`;
}

function inferTokens(project: Project): DesignTokens {
  const colors = project.blueprint?.colorScheme;
  const typography = project.blueprint?.typography;
  const flavor = `${project.brief?.tone || ""} ${project.blueprint?.brandPersonality || ""} ${project.blueprint?.designDirection || ""}`.toLowerCase();

  const playful = /playful|friendly|warm/.test(flavor);
  const luxury = /lux|premium|elegant|editorial/.test(flavor);
  const bold = /bold|edgy|expressive/.test(flavor);
  const minimal = /minimal|clean|technical|professional/.test(flavor);

  const primary = colors?.primary || "#7c3aed";
  const text = colors?.text || "#111111";
  const bg = colors?.bg || "#ffffff";
  const muted = colors?.muted || "#6b7280";

  return {
    primary,
    secondary: colors?.secondary || primary,
    accent: colors?.accent || primary,
    bg,
    text,
    muted,
    border: colors?.border || "rgba(15, 23, 42, 0.10)",
    sectionPadding: luxury ? "112px 40px" : bold ? "104px 36px" : minimal ? "88px 32px" : "96px 36px",
    containerWidth: luxury ? "1240px" : "1160px",
    radius: playful ? "28px" : luxury ? "22px" : minimal ? "16px" : "18px",
    buttonRadius: playful ? "999px" : luxury ? "16px" : "12px",
    shadow: luxury
      ? "0 18px 60px rgba(15, 23, 42, 0.16)"
      : minimal
      ? "0 10px 30px rgba(15, 23, 42, 0.08)"
      : "0 16px 44px rgba(15, 23, 42, 0.12)",
    softBg: `rgba(${hexToRgb(primary)}, 0.08)`,
    strongBg: bold || luxury ? text : primary,
    headingFont: typography?.headingFont || "Inter",
    bodyFont: typography?.bodyFont || "Inter",
  };
}

function shell(id: string, type: string, name: string, tokens: DesignTokens, inner: string, bg?: string): string {
  return `<section data-sz-section-id="${id}" data-sz-section-type="${type}" data-sz-section-name="${name}" style="padding:${tokens.sectionPadding};background:${bg || "transparent"};font-family:'${tokens.bodyFont}',system-ui,sans-serif;color:${tokens.text};"><div style="width:min(100%,${tokens.containerWidth});margin:0 auto;">${inner}</div></section>`;
}

export function buildBlockHtml(blockId: string, project: Project): string {
  const tokens = inferTokens(project);
  const siteName = project.blueprint?.siteName || project.name || "Brand";
  const tagline = project.blueprint?.tagline || project.brief?.description || "Describe what makes this project stand out.";
  const id = `sec-${uid()}`;
  const primaryGlow = `rgba(${hexToRgb(tokens.primary)}, 0.18)`;

  switch (blockId) {
    case "navbar":
    case "nav-simple":
      return `<nav data-sz-section-id="${id}" data-sz-section-type="navbar" data-sz-section-name="Navbar" style="position:sticky;top:0;z-index:40;padding:18px 32px;border-bottom:1px solid ${tokens.border};background:color-mix(in srgb, ${tokens.bg} 92%, white 8%);backdrop-filter:blur(18px);font-family:'${tokens.bodyFont}',system-ui,sans-serif;"><div style="width:min(100%,${tokens.containerWidth});margin:0 auto;display:flex;align-items:center;justify-content:space-between;gap:20px;"><a href="#" style="font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:22px;font-weight:800;color:${tokens.text};text-decoration:none;">${siteName}</a><div style="display:flex;align-items:center;gap:24px;flex-wrap:wrap;"><a href="#" style="color:${tokens.muted};text-decoration:none;font-size:14px;">Home</a><a href="#" style="color:${tokens.muted};text-decoration:none;font-size:14px;">About</a><a href="#" style="color:${tokens.muted};text-decoration:none;font-size:14px;">Services</a><a href="#" style="padding:12px 18px;border-radius:${tokens.buttonRadius};background:${tokens.primary};color:#fff;text-decoration:none;font-size:14px;font-weight:700;box-shadow:0 10px 26px ${primaryGlow};">Book a call</a></div></div></nav>`;
    case "navbar-center":
      return `<nav data-sz-section-id="${id}" data-sz-section-type="navbar" data-sz-section-name="Navbar Center" style="position:sticky;top:0;z-index:40;padding:16px 32px;border-bottom:1px solid ${tokens.border};background:${tokens.bg};font-family:'${tokens.bodyFont}',system-ui,sans-serif;"><div style="width:min(100%,${tokens.containerWidth});margin:0 auto;display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:20px;"><div style="display:flex;gap:20px;"><a href="#" style="color:${tokens.muted};text-decoration:none;font-size:14px;">Home</a><a href="#" style="color:${tokens.muted};text-decoration:none;font-size:14px;">Work</a><a href="#" style="color:${tokens.muted};text-decoration:none;font-size:14px;">About</a></div><a href="#" style="font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:22px;font-weight:800;color:${tokens.text};text-decoration:none;text-align:center;">${siteName}</a><div style="display:flex;justify-content:flex-end;"><a href="#" style="padding:10px 18px;border-radius:${tokens.buttonRadius};background:${tokens.primary};color:#fff;text-decoration:none;font-size:13px;font-weight:700;">Get started</a></div></div></nav>`;
    case "navbar-minimal":
      return `<nav data-sz-section-id="${id}" data-sz-section-type="navbar" data-sz-section-name="Navbar Minimal" style="position:sticky;top:0;z-index:40;padding:18px 32px;background:${tokens.bg};font-family:'${tokens.bodyFont}',system-ui,sans-serif;"><div style="width:min(100%,${tokens.containerWidth});margin:0 auto;display:flex;align-items:center;justify-content:space-between;"><a href="#" style="font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:22px;font-weight:800;color:${tokens.text};text-decoration:none;">${siteName}</a><a href="#" style="padding:12px 20px;border-radius:${tokens.buttonRadius};background:${tokens.primary};color:#fff;text-decoration:none;font-size:14px;font-weight:700;">Book a call</a></div></nav>`;
    case "hero":
    case "hero-centered":
      return shell(id, "hero", "Hero", tokens, `<div style="display:grid;gap:28px;justify-items:start;text-align:left;"><span style="display:inline-flex;align-items:center;gap:8px;padding:8px 14px;border-radius:999px;background:${tokens.softBg};border:1px solid ${primaryGlow};font-size:11px;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;color:${tokens.primary};">New launch</span><div style="max-width:760px;"><h1 style="margin:0 0 18px;font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:clamp(42px,7vw,82px);line-height:0.98;letter-spacing:-0.04em;color:${tokens.text};">Built for clarity.<br/><span style="color:${tokens.primary};">Designed to convert.</span></h1><p style="margin:0;max-width:620px;font-size:18px;line-height:1.75;color:${tokens.muted};">${tagline}</p></div><div style="display:flex;gap:14px;flex-wrap:wrap;"><a href="#" style="display:inline-flex;align-items:center;justify-content:center;padding:16px 24px;border-radius:${tokens.buttonRadius};background:${tokens.primary};color:#fff;text-decoration:none;font-size:15px;font-weight:700;box-shadow:0 14px 32px ${primaryGlow};">Get started</a><a href="#" style="display:inline-flex;align-items:center;justify-content:center;padding:16px 24px;border-radius:${tokens.buttonRadius};border:1px solid ${tokens.border};background:${tokens.bg};color:${tokens.text};text-decoration:none;font-size:15px;font-weight:600;">View work</a></div></div>`);
    case "hero-split":
      return shell(id, "hero-split", "Hero Split", tokens, `<div style="display:grid;grid-template-columns:1fr 1fr;gap:40px;align-items:center;"><div style="display:grid;gap:22px;"><h1 style="margin:0;font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:clamp(36px,5vw,64px);line-height:1.02;letter-spacing:-0.03em;color:${tokens.text};">${siteName}<br/><span style="color:${tokens.primary};">for bold brands.</span></h1><p style="margin:0;font-size:17px;line-height:1.8;color:${tokens.muted};">${tagline}</p><div style="display:flex;gap:12px;flex-wrap:wrap;"><a href="#" style="padding:14px 24px;border-radius:${tokens.buttonRadius};background:${tokens.primary};color:#fff;text-decoration:none;font-size:14px;font-weight:700;box-shadow:0 12px 28px ${primaryGlow};">Get started</a><a href="#" style="padding:14px 24px;border-radius:${tokens.buttonRadius};border:1px solid ${tokens.border};color:${tokens.text};text-decoration:none;font-size:14px;font-weight:600;">Learn more</a></div></div><div style="border-radius:${tokens.radius};overflow:hidden;box-shadow:${tokens.shadow};"><img src="https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=900&q=80" alt="Hero" style="width:100%;height:420px;object-fit:cover;display:block;" /></div></div>`);
    case "section":
    case "section-basic":
      return shell(id, "section", "Section", tokens, `<div style="padding:32px;border:1px solid ${tokens.border};border-radius:${tokens.radius};background:${tokens.bg};box-shadow:${tokens.shadow};"><h2 style="margin:0 0 12px;font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:32px;line-height:1.1;color:${tokens.text};">New section title</h2><p style="margin:0;font-size:16px;line-height:1.75;color:${tokens.muted};">Add content here and adjust it from the properties panel.</p></div>`);
    case "container":
      return shell(id, "container", "Container", tokens, `<div style="min-height:160px;padding:28px;border-radius:${tokens.radius};border:1px dashed ${tokens.border};background:${tokens.softBg};display:flex;align-items:center;justify-content:center;text-align:center;"><p style="margin:0;font-size:14px;color:${tokens.muted};">Container ready for nested content</p></div>`);
    case "heading":
      return shell(id, "heading", "Heading", tokens, `<div style="text-align:center;"><h2 style="margin:0 0 12px;font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:clamp(30px,5vw,56px);line-height:1.02;letter-spacing:-0.03em;color:${tokens.text};">Section heading</h2><p style="margin:0 auto;max-width:620px;font-size:17px;line-height:1.75;color:${tokens.muted};">Supporting copy that matches the current site voice and spacing rhythm.</p></div>`);
    case "paragraph":
      return shell(id, "paragraph", "Paragraph", tokens, `<div style="max-width:760px;"><p style="margin:0;font-size:18px;line-height:1.85;color:${tokens.text};opacity:0.88;">This paragraph inherits the current project palette, typography, spacing, and tone so it feels native to the existing design.</p></div>`);
    case "button":
      return shell(id, "button", "Button", tokens, `<div style="display:flex;justify-content:center;"><a href="#" style="display:inline-flex;align-items:center;justify-content:center;padding:16px 24px;border-radius:${tokens.buttonRadius};background:${tokens.primary};color:#fff;text-decoration:none;font-size:15px;font-weight:700;box-shadow:0 14px 32px ${primaryGlow};">Primary action</a></div>`);
    case "image":
      return shell(id, "image", "Image", tokens, `<figure style="margin:0;border-radius:${tokens.radius};overflow:hidden;border:1px solid ${tokens.border};box-shadow:${tokens.shadow};background:${tokens.softBg};"><img src="https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=80" alt="Project visual" style="width:100%;height:420px;object-fit:cover;display:block;" /><figcaption style="padding:14px 18px;font-size:13px;color:${tokens.muted};background:${tokens.bg};">Replace this image from the properties panel.</figcaption></figure>`);
    case "grid":
      return shell(id, "grid", "Grid", tokens, `<div style="display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px;">${[1,2,3].map((index) => `<div style="padding:28px;border-radius:${tokens.radius};background:${tokens.bg};border:1px solid ${tokens.border};box-shadow:${tokens.shadow};"><h3 style="margin:0 0 8px;font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:20px;color:${tokens.text};">Grid item ${index}</h3><p style="margin:0;font-size:14px;line-height:1.7;color:${tokens.muted};">Editable content block that follows the project system.</p></div>`).join("")}</div>`, tokens.softBg);
    case "columns":
      return shell(id, "columns", "Columns", tokens, `<div style="display:grid;grid-template-columns:1.2fr .8fr;gap:24px;align-items:start;"><div style="padding:28px;border-radius:${tokens.radius};background:${tokens.bg};border:1px solid ${tokens.border};box-shadow:${tokens.shadow};"><h3 style="margin:0 0 10px;font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:28px;color:${tokens.text};">Two-column layout</h3><p style="margin:0;font-size:15px;line-height:1.75;color:${tokens.muted};">Use this for content paired with supporting detail, stats, or a call to action.</p></div><div style="padding:28px;border-radius:${tokens.radius};background:${tokens.softBg};border:1px solid ${tokens.border};"><p style="margin:0 0 6px;font-size:12px;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;color:${tokens.primary};">Quick note</p><p style="margin:0;font-size:14px;line-height:1.75;color:${tokens.text};">Everything stays editable after insertion.</p></div></div>`);
    case "features":
    case "features-3":
      return shell(id, "features", "Features", tokens, `<div style="text-align:center;margin-bottom:28px;"><h2 style="margin:0 0 12px;font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:clamp(30px,5vw,48px);color:${tokens.text};">Core features</h2><p style="margin:0 auto;max-width:620px;font-size:16px;line-height:1.75;color:${tokens.muted};">Add or rewrite each card to match the offer on this page.</p></div><div style="display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px;">${["Fast setup","Refined output","Reliable delivery"].map((title, index) => `<article style="padding:28px;border-radius:${tokens.radius};background:${tokens.bg};border:1px solid ${tokens.border};box-shadow:${tokens.shadow};text-align:left;"><div style="width:44px;height:44px;border-radius:${tokens.buttonRadius};background:${tokens.softBg};display:flex;align-items:center;justify-content:center;margin-bottom:18px;font-size:20px;color:${tokens.primary};">${["✦","◎","→"][index]}</div><h3 style="margin:0 0 10px;font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:21px;color:${tokens.text};">${title}</h3><p style="margin:0;font-size:14px;line-height:1.75;color:${tokens.muted};">Insert blocks that inherit the site tone instead of clashing with it.</p></article>`).join("")}</div>`, tokens.softBg);
    case "testimonial":
      return shell(id, "testimonial", "Testimonial", tokens, `<div style="padding:36px;border-radius:${tokens.radius};background:${tokens.bg};border:1px solid ${tokens.border};box-shadow:${tokens.shadow};text-align:center;"><div style="font-size:42px;line-height:1;color:${tokens.primary};margin-bottom:16px;">“</div><blockquote style="margin:0 auto 20px;max-width:760px;font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:28px;line-height:1.4;color:${tokens.text};">This section now drops in with the same visual language as the rest of the site.</blockquote><div style="display:inline-flex;align-items:center;gap:12px;"><div style="width:46px;height:46px;border-radius:999px;background:${tokens.softBg};display:flex;align-items:center;justify-content:center;color:${tokens.primary};font-weight:700;">SJ</div><div style="text-align:left;"><p style="margin:0;font-size:14px;font-weight:700;color:${tokens.text};">Sarah Johnson</p><p style="margin:0;font-size:13px;color:${tokens.muted};">Founder, ${siteName}</p></div></div></div>`, tokens.softBg);
    case "gallery":
      return shell(id, "gallery", "Gallery", tokens, `<div style="display:grid;gap:18px;grid-template-columns:1.4fr 1fr 1fr;"><img src="https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80" alt="Gallery item 1" style="width:100%;height:420px;object-fit:cover;border-radius:${tokens.radius};box-shadow:${tokens.shadow};" /><div style="display:grid;gap:18px;">${["photo-1498050108023-c5249f4df085","photo-1517248135467-4c7edcad34c4"].map((key, index) => `<img src="https://images.unsplash.com/${key}?auto=format&fit=crop&w=900&q=80" alt="Gallery item ${index + 2}" style="width:100%;height:201px;object-fit:cover;border-radius:${tokens.radius};box-shadow:${tokens.shadow};" />`).join("")}</div><div style="padding:28px;border-radius:${tokens.radius};background:${tokens.bg};border:1px solid ${tokens.border};box-shadow:${tokens.shadow};display:flex;flex-direction:column;justify-content:center;"><p style="margin:0 0 8px;font-size:12px;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;color:${tokens.primary};">Gallery</p><h3 style="margin:0 0 10px;font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:28px;color:${tokens.text};">Show the work visually</h3><p style="margin:0;font-size:14px;line-height:1.75;color:${tokens.muted};">Images inherit the site framing, radius, and shadow system.</p></div></div>`);
    case "cta":
    case "cta-solid":
      return shell(id, "cta", "Call To Action", tokens, `<div style="padding:44px;border-radius:${tokens.radius};background:${tokens.strongBg};box-shadow:${tokens.shadow};text-align:center;"><h2 style="margin:0 0 14px;font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:clamp(30px,5vw,48px);color:${tokens.bg};">Ready to move faster?</h2><p style="margin:0 auto 24px;max-width:620px;font-size:17px;line-height:1.75;color:rgba(255,255,255,0.76);">Add a strong CTA that still feels native to the current brand system.</p><div style="display:flex;gap:14px;justify-content:center;flex-wrap:wrap;"><a href="#" style="padding:16px 24px;border-radius:${tokens.buttonRadius};background:${tokens.bg};color:${tokens.strongBg};text-decoration:none;font-size:15px;font-weight:700;">Start now</a><a href="#" style="padding:16px 24px;border-radius:${tokens.buttonRadius};border:1px solid rgba(255,255,255,0.18);color:${tokens.bg};text-decoration:none;font-size:15px;font-weight:600;">Talk to sales</a></div></div>`);
    case "split-image":
      return shell(id, "split-image", "Split Image", tokens, `<div style="display:grid;grid-template-columns:1fr 1fr;gap:32px;align-items:center;"><img src="https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=900&q=80" alt="Visual" style="width:100%;height:460px;object-fit:cover;border-radius:${tokens.radius};box-shadow:${tokens.shadow};display:block;" /><div style="display:grid;gap:16px;"><span style="display:inline-flex;padding:6px 12px;border-radius:999px;background:${tokens.softBg};font-size:11px;font-weight:700;letter-spacing:.1em;text-transform:uppercase;color:${tokens.primary};width:max-content;">Feature</span><h2 style="margin:0;font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:clamp(28px,4vw,48px);line-height:1.08;color:${tokens.text};">Content that converts on sight</h2><p style="margin:0;font-size:16px;line-height:1.8;color:${tokens.muted};">Pair compelling copy with a strong visual. Adjust everything from the style panel.</p><a href="#" style="display:inline-flex;align-items:center;gap:8px;padding:14px 22px;border-radius:${tokens.buttonRadius};background:${tokens.primary};color:#fff;text-decoration:none;font-size:14px;font-weight:700;width:max-content;box-shadow:0 10px 26px ${primaryGlow};">Learn more →</a></div></div>`);
    case "stats":
      return shell(id, "stats", "Stats", tokens, `<div style="text-align:center;margin-bottom:28px;"><h2 style="margin:0 0 10px;font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:clamp(28px,4vw,44px);color:${tokens.text};">By the numbers</h2><p style="margin:0 auto;max-width:540px;font-size:15px;color:${tokens.muted};">Real results that speak for themselves.</p></div><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:16px;">${[["98%","Customer satisfaction"],["2.4×","Average ROI",""],["10k+","Active users"],["< 48h","Response time"]].map(([val, label]) => `<div style="padding:28px 20px;border-radius:${tokens.radius};background:${tokens.bg};border:1px solid ${tokens.border};text-align:center;box-shadow:${tokens.shadow};"><div style="font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:40px;font-weight:800;color:${tokens.primary};line-height:1;">${val}</div><div style="margin-top:8px;font-size:13px;color:${tokens.muted};">${label}</div></div>`).join("")}`, tokens.softBg);
    case "timeline":
      return shell(id, "timeline", "Timeline", tokens, `<div style="text-align:center;margin-bottom:32px;"><h2 style="margin:0 0 10px;font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:clamp(28px,4vw,44px);color:${tokens.text};">How it works</h2></div><div style="display:grid;gap:0;position:relative;">${["Discover","Design","Deliver"].map((step, i) => `<div style="display:grid;grid-template-columns:80px 1fr;gap:20px;padding:24px 0;${i < 2 ? `border-left:2px solid ${tokens.border};margin-left:39px;padding-left:28px;` : ""}"><div style="width:44px;height:44px;border-radius:999px;background:${tokens.primary};color:#fff;font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:18px;font-weight:800;display:flex;align-items:center;justify-content:center;flex-shrink:0;margin-left:${i > 0 ? "-50px" : "-22px"};box-shadow:0 8px 20px ${primaryGlow};">${i + 1}</div><div><h3 style="margin:0 0 6px;font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:20px;color:${tokens.text};">${step}</h3><p style="margin:0;font-size:14px;line-height:1.75;color:${tokens.muted};">Brief description of this step goes here. Edit to match your process.</p></div></div>`).join("")}</div>`);
    case "features-list":
      return shell(id, "features-list", "Feature List", tokens, `<div style="display:grid;grid-template-columns:1fr 1fr;gap:32px;align-items:center;"><div><h2 style="margin:0 0 14px;font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:clamp(28px,4vw,44px);color:${tokens.text};">Everything you need</h2><p style="margin:0 0 28px;font-size:16px;line-height:1.8;color:${tokens.muted};">A complete toolkit built to help you move fast and look great.</p></div><div style="display:grid;gap:16px;">${["Zero setup required","Fully customisable","Production-ready output","Priority support"].map(f => `<div style="display:flex;align-items:flex-start;gap:14px;padding:18px;border-radius:${tokens.radius};background:${tokens.bg};border:1px solid ${tokens.border};"><div style="width:32px;height:32px;border-radius:${tokens.buttonRadius};background:${tokens.softBg};display:flex;align-items:center;justify-content:center;flex-shrink:0;color:${tokens.primary};font-weight:700;">✓</div><div><p style="margin:0;font-size:15px;font-weight:600;color:${tokens.text};">${f}</p><p style="margin:4px 0 0;font-size:13px;color:${tokens.muted};">Short supporting detail.</p></div></div>`).join("")}</div></div>`);
    case "testimonials":
      return shell(id, "testimonials", "Testimonials", tokens, `<div style="text-align:center;margin-bottom:28px;"><h2 style="margin:0 0 10px;font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:clamp(28px,4vw,44px);color:${tokens.text};">What people say</h2></div><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:18px;">${[["Alex R.","CEO, Axiom","The results spoke for themselves. We moved faster than ever."],["Priya S.","Designer","Blocks that actually match the brand. Rare and genuinely useful."],["James K.","Founder","This alone saved us three weeks of back-and-forth."]].map(([name, role, quote]) => `<div style="padding:28px;border-radius:${tokens.radius};background:${tokens.bg};border:1px solid ${tokens.border};box-shadow:${tokens.shadow};"><div style="font-size:28px;color:${tokens.primary};margin-bottom:12px;">"</div><p style="margin:0 0 20px;font-size:15px;line-height:1.75;color:${tokens.text};">${quote}</p><div style="display:flex;align-items:center;gap:10px;"><div style="width:36px;height:36px;border-radius:999px;background:${tokens.softBg};display:flex;align-items:center;justify-content:center;font-size:12px;font-weight:700;color:${tokens.primary};">${name[0]}</div><div><p style="margin:0;font-size:13px;font-weight:700;color:${tokens.text};">${name}</p><p style="margin:0;font-size:12px;color:${tokens.muted};">${role}</p></div></div></div>`).join("")}`, tokens.softBg);
    case "team":
      return shell(id, "team", "Team", tokens, `<div style="text-align:center;margin-bottom:28px;"><h2 style="margin:0 0 10px;font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:clamp(28px,4vw,44px);color:${tokens.text};">Meet the team</h2><p style="margin:0 auto;max-width:520px;font-size:15px;color:${tokens.muted};">The people behind the work.</p></div><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:18px;">${[["Alex M.","Co-founder & CEO","photo-1507003211169-0a1dd7228f2d"],["Priya K.","Head of Design","photo-1573496359142-b8d87734a5a2"],["Sam T.","Lead Engineer","photo-1519085360753-af0119f7cbe7"],["Zoe L.","Growth","photo-1580489944761-15a19d654956"]].map(([name, role, photo]) => `<div style="text-align:center;padding:24px 16px;border-radius:${tokens.radius};background:${tokens.bg};border:1px solid ${tokens.border};box-shadow:${tokens.shadow};"><img src="https://images.unsplash.com/${photo}?auto=format&fit=crop&w=300&q=80" alt="${name}" style="width:72px;height:72px;border-radius:999px;object-fit:cover;display:block;margin:0 auto 14px;" /><p style="margin:0 0 4px;font-size:15px;font-weight:700;color:${tokens.text};">${name}</p><p style="margin:0;font-size:12px;color:${tokens.muted};">${role}</p></div>`).join("")}`);
    case "pricing":
      return shell(id, "pricing", "Pricing", tokens, `<div style="text-align:center;margin-bottom:32px;"><h2 style="margin:0 0 10px;font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:clamp(28px,4vw,44px);color:${tokens.text};">Simple pricing</h2><p style="margin:0 auto;max-width:520px;font-size:15px;color:${tokens.muted};">No hidden fees. Pick a plan and get started today.</p></div><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:18px;align-items:start;">${[["Starter","49","For individuals just getting started.",["5 projects","Basic analytics","Email support"]],["Pro","99","Perfect for growing teams.",["Unlimited projects","Advanced analytics","Priority support","Custom domain"]],["Enterprise","249","For large organisations at scale.",["Everything in Pro","Dedicated manager","SLA & compliance","SSO & audit logs"]]].map(([name, price, desc, features], i) => `<div style="padding:28px;border-radius:${tokens.radius};background:${i === 1 ? tokens.primary : tokens.bg};border:${i === 1 ? `2px solid ${tokens.primary}` : `1px solid ${tokens.border}`};box-shadow:${i === 1 ? `0 20px 60px ${primaryGlow}` : tokens.shadow};"><p style="margin:0 0 6px;font-size:12px;font-weight:700;letter-spacing:.1em;text-transform:uppercase;color:${i === 1 ? "rgba(255,255,255,.7)" : tokens.primary};">${name}</p><div style="display:flex;align-items:baseline;gap:2px;margin:0 0 10px;"><span style="font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:48px;font-weight:800;color:${i === 1 ? "#fff" : tokens.text};">$${price}</span><span style="font-size:13px;color:${i === 1 ? "rgba(255,255,255,.6)" : tokens.muted};">/mo</span></div><p style="margin:0 0 18px;font-size:13px;line-height:1.7;color:${i === 1 ? "rgba(255,255,255,.75)" : tokens.muted};">${desc}</p><ul style="margin:0 0 22px;padding:0;list-style:none;display:grid;gap:8px;">${(features as string[]).map(f => `<li style="display:flex;align-items:center;gap:8px;font-size:13px;color:${i === 1 ? "rgba(255,255,255,.85)" : tokens.text};"><span style="color:${i === 1 ? "#fff" : tokens.primary};font-weight:700;">✓</span>${f}</li>`).join("")}</ul><a href="#" style="display:block;text-align:center;padding:13px;border-radius:${tokens.buttonRadius};background:${i === 1 ? "#fff" : tokens.primary};color:${i === 1 ? tokens.primary : "#fff"};text-decoration:none;font-size:14px;font-weight:700;">Get started</a></div>`).join("")}`);
    case "faq":
      return shell(id, "faq", "FAQ", tokens, `<div style="text-align:center;margin-bottom:32px;"><h2 style="margin:0 0 10px;font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:clamp(28px,4vw,44px);color:${tokens.text};">Frequently asked</h2></div><div style="max-width:760px;margin:0 auto;display:grid;gap:12px;">${[["How does it work?","Each block inherits the project's color palette, typography, and spacing so it fits immediately without manual tweaking."],["Can I edit blocks after inserting?","Yes — click any element on the canvas to select and style it. Drag, resize, and reorder from the toolbar."],["What happens when I export?","A clean, production-ready ZIP is generated with HTML, CSS, and assets. No lock-in."],["Is support available?","Yes. Priority support is included on all plans above Starter."]].map(([q, a]) => `<details style="border:1px solid ${tokens.border};border-radius:${tokens.radius};background:${tokens.bg};overflow:hidden;"><summary style="padding:18px 22px;font-size:15px;font-weight:600;color:${tokens.text};cursor:pointer;list-style:none;display:flex;justify-content:space-between;align-items:center;">${q}<span style="font-size:20px;color:${tokens.muted};">+</span></summary><p style="margin:0;padding:0 22px 18px;font-size:14px;line-height:1.8;color:${tokens.muted};">${a}</p></details>`).join("")}`);
    case "logo-wall":
      return shell(id, "logo-wall", "Logo Wall", tokens, `<div style="text-align:center;margin-bottom:24px;"><p style="margin:0;font-size:12px;font-weight:700;letter-spacing:.12em;text-transform:uppercase;color:${tokens.muted};">Trusted by teams at</p></div><div style="display:flex;align-items:center;justify-content:center;gap:32px;flex-wrap:wrap;">${["Vercel","Linear","Figma","Stripe","Notion","Loom"].map(name => `<div style="padding:12px 22px;border-radius:${tokens.buttonRadius};border:1px solid ${tokens.border};background:${tokens.bg};font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:15px;font-weight:800;color:${tokens.muted};letter-spacing:-.02em;">${name}</div>`).join("")}`, tokens.softBg);
    case "cta-strip":
      return shell(id, "cta-strip", "CTA Strip", tokens, `<div style="display:flex;align-items:center;justify-content:space-between;gap:20px;flex-wrap:wrap;padding:28px 32px;border-radius:${tokens.radius};background:${tokens.softBg};border:1px solid ${primaryGlow};"><div><h3 style="margin:0 0 4px;font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:22px;color:${tokens.text};">Ready to get started?</h3><p style="margin:0;font-size:14px;color:${tokens.muted};">Join thousands of teams already using ${siteName}.</p></div><a href="#" style="padding:14px 24px;border-radius:${tokens.buttonRadius};background:${tokens.primary};color:#fff;text-decoration:none;font-size:14px;font-weight:700;white-space:nowrap;box-shadow:0 12px 28px ${primaryGlow};">Start free →</a></div>`);
    case "newsletter":
      return shell(id, "newsletter", "Newsletter", tokens, `<div style="text-align:center;max-width:560px;margin:0 auto;display:grid;gap:20px;"><h2 style="margin:0;font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:clamp(28px,4vw,44px);color:${tokens.text};">Stay in the loop</h2><p style="margin:0;font-size:16px;line-height:1.8;color:${tokens.muted};">Get insights, product updates, and resources delivered to your inbox.</p><form style="display:flex;gap:10px;"><input type="email" placeholder="Your email address" style="flex:1;padding:14px 18px;border-radius:${tokens.buttonRadius};border:1px solid ${tokens.border};background:${tokens.bg};color:${tokens.text};font-size:14px;outline:none;font-family:'${tokens.bodyFont}',system-ui,sans-serif;" /><button type="submit" style="padding:14px 22px;border-radius:${tokens.buttonRadius};background:${tokens.primary};color:#fff;font-size:14px;font-weight:700;border:none;cursor:pointer;white-space:nowrap;box-shadow:0 10px 24px ${primaryGlow};">Subscribe</button></form><p style="margin:0;font-size:12px;color:${tokens.muted};">No spam. Unsubscribe any time.</p></div>`);
    case "footer":
    case "footer-simple":
      return `<footer data-sz-section-id="${id}" data-sz-section-type="footer" data-sz-section-name="Footer" style="padding:36px 32px;background:${tokens.text};color:#fff;font-family:'${tokens.bodyFont}',system-ui,sans-serif;"><div style="width:min(100%,${tokens.containerWidth});margin:0 auto;display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap;"><div><strong style="display:block;font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:18px;">${siteName}</strong><span style="font-size:13px;color:rgba(255,255,255,0.55);">${tagline.slice(0, 72)}</span></div><div style="display:flex;gap:20px;flex-wrap:wrap;"><a href="#" style="color:rgba(255,255,255,0.7);text-decoration:none;font-size:14px;">Privacy</a><a href="#" style="color:rgba(255,255,255,0.7);text-decoration:none;font-size:14px;">Terms</a><a href="#" style="color:rgba(255,255,255,0.7);text-decoration:none;font-size:14px;">Contact</a></div></div></footer>`;
    case "footer-columns":
      return `<footer data-sz-section-id="${id}" data-sz-section-type="footer" data-sz-section-name="Footer Columns" style="padding:56px 32px 28px;background:${tokens.text};color:#fff;font-family:'${tokens.bodyFont}',system-ui,sans-serif;"><div style="width:min(100%,${tokens.containerWidth});margin:0 auto;"><div style="display:grid;grid-template-columns:2fr 1fr 1fr 1fr;gap:32px;margin-bottom:40px;"><div><strong style="display:block;font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:20px;margin-bottom:10px;">${siteName}</strong><p style="margin:0 0 16px;font-size:13px;line-height:1.75;color:rgba(255,255,255,.5);max-width:220px;">${tagline.slice(0,80)}</p></div>${["Product","Company","Legal"].map(col => `<div><p style="margin:0 0 14px;font-size:12px;font-weight:700;letter-spacing:.1em;text-transform:uppercase;color:rgba(255,255,255,.35);">${col}</p><div style="display:grid;gap:10px;">${["Overview","Pricing","Changelog"].map(l=>`<a href="#" style="color:rgba(255,255,255,.6);text-decoration:none;font-size:13px;">${l}</a>`).join("")}</div></div>`).join("")}</div><div style="border-top:1px solid rgba(255,255,255,.08);padding-top:20px;display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:12px;"><span style="font-size:12px;color:rgba(255,255,255,.3);">© ${new Date().getFullYear()} ${siteName}. All rights reserved.</span></div></div></footer>`;
    default:
      return shell(id, "section", "Section", tokens, `<div style="padding:28px;border-radius:${tokens.radius};background:${tokens.bg};border:1px solid ${tokens.border};box-shadow:${tokens.shadow};"><h3 style="margin:0 0 10px;font-family:'${tokens.headingFont}',system-ui,sans-serif;color:${tokens.text};">${blockId}</h3><p style="margin:0;color:${tokens.muted};line-height:1.75;">This block was inserted using the current project design tokens.</p></div>`);
  }
}

/** HTML for inline elements — no section shell, ready to append inside an existing section container. */
export function buildInlineHtml(blockId: string, project: Project): string {
  const tokens = inferTokens(project);
  const primaryGlow = `rgba(${hexToRgb(tokens.primary)}, 0.18)`;

  switch (blockId) {
    case "heading":
      return `<div style="margin:0 0 24px;"><h2 style="margin:0 0 10px;font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:clamp(26px,4vw,44px);line-height:1.08;letter-spacing:-0.02em;color:${tokens.text};">Section Heading</h2><p style="margin:0;font-size:16px;line-height:1.75;color:${tokens.muted};">Supporting subtext that matches the site voice.</p></div>`;
    case "paragraph":
      return `<p style="margin:0 0 20px;font-size:17px;line-height:1.85;color:${tokens.text};">This paragraph inherits the current project palette, typography, and tone so it feels native to the design. Click to edit.</p>`;
    case "button":
      return `<div style="margin:0 0 20px;"><a href="#" style="display:inline-flex;align-items:center;justify-content:center;padding:14px 24px;border-radius:${tokens.buttonRadius};background:${tokens.primary};color:#fff;text-decoration:none;font-size:15px;font-weight:700;box-shadow:0 10px 26px ${primaryGlow};">Primary action</a></div>`;
    case "button-outline":
      return `<div style="margin:0 0 20px;"><a href="#" style="display:inline-flex;align-items:center;justify-content:center;padding:14px 24px;border-radius:${tokens.buttonRadius};border:1.5px solid ${tokens.primary};background:transparent;color:${tokens.primary};text-decoration:none;font-size:15px;font-weight:700;">Secondary action</a></div>`;
    case "badge":
      return `<div style="margin:0 0 16px;"><span style="display:inline-flex;align-items:center;padding:6px 14px;border-radius:999px;background:${tokens.softBg};border:1px solid rgba(${hexToRgb(tokens.primary)},0.22);font-size:12px;font-weight:700;letter-spacing:0.08em;text-transform:uppercase;color:${tokens.primary};">Label</span></div>`;
    case "blockquote":
      return `<blockquote style="margin:0 0 20px;padding:20px 24px;border-left:4px solid ${tokens.primary};background:${tokens.softBg};border-radius:0 ${tokens.radius} ${tokens.radius} 0;font-size:18px;line-height:1.7;color:${tokens.text};font-style:italic;">"A compelling pull-quote that anchors the reader's attention and builds credibility."</blockquote>`;
    case "divider":
      return `<hr style="margin:16px 0;border:none;border-top:1px solid ${tokens.border};" />`;
    case "spacer":
      return `<div style="height:80px;" aria-hidden="true"></div>`;
    case "image":
      return `<figure style="margin:0 0 20px;border-radius:${tokens.radius};overflow:hidden;border:1px solid ${tokens.border};box-shadow:${tokens.shadow};"><img src="https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80" alt="Image" style="width:100%;height:320px;object-fit:cover;display:block;" /><figcaption style="padding:10px 16px;font-size:12px;color:${tokens.muted};background:${tokens.bg};">Replace with your image from the style panel.</figcaption></figure>`;
    case "video":
      return `<div style="margin:0 0 20px;border-radius:${tokens.radius};overflow:hidden;background:#000;position:relative;padding-bottom:56.25%;box-shadow:${tokens.shadow};"><div style="position:absolute;inset:0;display:flex;align-items:center;justify-content:center;"><div style="width:64px;height:64px;border-radius:999px;background:rgba(255,255,255,.18);display:flex;align-items:center;justify-content:center;"><span style="color:#fff;font-size:26px;margin-left:4px;">▶</span></div></div></div>`;
    case "icon-block":
      return `<div style="display:flex;align-items:flex-start;gap:16px;margin:0 0 20px;padding:20px;border-radius:${tokens.radius};background:${tokens.bg};border:1px solid ${tokens.border};"><div style="width:44px;height:44px;border-radius:${tokens.buttonRadius};background:${tokens.softBg};display:flex;align-items:center;justify-content:center;flex-shrink:0;font-size:20px;color:${tokens.primary};">◈</div><div><h4 style="margin:0 0 6px;font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:16px;font-weight:700;color:${tokens.text};">Icon block title</h4><p style="margin:0;font-size:14px;line-height:1.75;color:${tokens.muted};">Supporting description for this feature or benefit.</p></div></div>`;
    case "card":
      return `<div style="margin:0 0 20px;padding:24px;border-radius:${tokens.radius};background:${tokens.bg};border:1px solid ${tokens.border};box-shadow:${tokens.shadow};"><h3 style="margin:0 0 10px;font-family:'${tokens.headingFont}',system-ui,sans-serif;font-size:20px;color:${tokens.text};">Card title</h3><p style="margin:0;font-size:14px;line-height:1.75;color:${tokens.muted};">Card content that matches the site's visual language and spacing.</p></div>`;
    case "contact-form":
      return `<form style="display:grid;gap:14px;max-width:520px;" onsubmit="return false;"><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;"><div><label style="display:block;margin-bottom:6px;font-size:13px;font-weight:600;color:${tokens.text};">Name</label><input type="text" placeholder="Your name" style="width:100%;padding:12px 16px;border-radius:${tokens.buttonRadius};border:1px solid ${tokens.border};background:${tokens.bg};color:${tokens.text};font-size:14px;outline:none;box-sizing:border-box;" /></div><div><label style="display:block;margin-bottom:6px;font-size:13px;font-weight:600;color:${tokens.text};">Email</label><input type="email" placeholder="you@example.com" style="width:100%;padding:12px 16px;border-radius:${tokens.buttonRadius};border:1px solid ${tokens.border};background:${tokens.bg};color:${tokens.text};font-size:14px;outline:none;box-sizing:border-box;" /></div></div><div><label style="display:block;margin-bottom:6px;font-size:13px;font-weight:600;color:${tokens.text};">Message</label><textarea rows="4" placeholder="Your message…" style="width:100%;padding:12px 16px;border-radius:${tokens.buttonRadius};border:1px solid ${tokens.border};background:${tokens.bg};color:${tokens.text};font-size:14px;outline:none;resize:vertical;box-sizing:border-box;"></textarea></div><button type="submit" style="padding:14px 22px;border-radius:${tokens.buttonRadius};background:${tokens.primary};color:#fff;font-size:14px;font-weight:700;border:none;cursor:pointer;width:max-content;box-shadow:0 10px 24px ${primaryGlow};">Send message</button></form>`;
    default:
      return `<div style="padding:12px;border-radius:${tokens.radius};background:${tokens.softBg};border:1px dashed ${tokens.border};font-size:13px;color:${tokens.muted};">${blockId}</div>`;
  }
}
