import type {
  BlueprintPage,
  Project,
  ProjectGenerationJob,
  ProjectPage,
  ProjectSnapshot,
  SiteBlueprint,
  SiteBrief,
  VirtualFile,
} from "@/types";
import {
  API_GENERATE_001,
  AUTH_PERMISSION_001,
  DB_READ_002,
  createAppError,
  normalizeError,
} from "@/lib/errors";
import { generateBlueprint, generatePage } from "@/lib/ai/service";
import { consumeAIUsageCredits } from "@/lib/server/launch-usage";
import {
  completeGenerationJob,
  failGenerationJob,
  getGenerationJobById,
  touchGenerationJob,
  updateGenerationJob,
} from "@/lib/server/project-generation-jobs";
import { getProjectSnapshot, saveProjectSnapshot } from "@/lib/server/project-db";
import { extractNavbarHtml } from "@/lib/utils";

export interface ProjectGenerationStepResult {
  job: ProjectGenerationJob;
  shouldContinue: boolean;
}

function buildGenerationStylesheet(blueprint: SiteBlueprint): string {
  const { colorScheme, typography } = blueprint;
  return `/* Generated by Sitezy */
:root {
  --color-primary: ${colorScheme.primary};
  --color-secondary: ${colorScheme.secondary};
  --color-accent: ${colorScheme.accent};
  --color-bg: ${colorScheme.bg};
  --color-text: ${colorScheme.text};
  --color-muted: ${colorScheme.muted || "#6b7280"};
  --font-heading: '${typography.headingFont}', sans-serif;
  --font-body: '${typography.bodyFont}', system-ui, sans-serif;
}
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: var(--font-body); background: var(--color-bg); color: var(--color-text); line-height: 1.6; }
h1, h2, h3, h4, h5, h6 { font-family: var(--font-heading); line-height: 1.2; }
a { color: var(--color-primary); text-decoration: none; }
img { max-width: 100%; height: auto; }
`;
}

function buildInitialFiles(blueprint: SiteBlueprint): Record<string, VirtualFile> {
  return {
    "styles-global": {
      id: "styles-global",
      name: "styles.css",
      path: "/styles/global.css",
      content: buildGenerationStylesheet(blueprint),
      type: "css",
      language: "css",
    },
  };
}

function buildPendingPages(blueprint: SiteBlueprint): ProjectPage[] {
  return blueprint.pages.map((page) => ({
    id: page.id,
    name: page.name,
    slug: page.slug,
    purpose: page.purpose,
    sections: [],
    html: "",
    status: "pending",
  }));
}

function resolveBlueprintPage(project: Project, page: ProjectPage): BlueprintPage {
  const bySlug = project.blueprint?.pages.find((entry) => entry.slug === page.slug);
  if (bySlug) return bySlug;

  const byName = project.blueprint?.pages.find((entry) => entry.name === page.name);
  if (byName) return byName;

  return {
    id: page.slug || page.name.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
    name: page.name,
    slug: page.slug || page.name.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
    purpose: page.purpose,
    sections: page.sections.map((section) => section.type || section.name.toLowerCase()) || ["hero", "content", "cta"],
  };
}

function replaceLogoPlaceholders(html: string, brief: SiteBrief): string {
  const logoUrl = brief.smartBrief?.logoUrl?.trim();
  if (!logoUrl || !html.includes("__LOGO__")) {
    return html;
  }
  return html.replaceAll("__LOGO__", logoUrl);
}

function normalizeGeneratedHtml(html: string, brief: SiteBrief): string {
  const fixedHrefHtml = html.replace(/href="\/\/([^"]*?)"/g, (_match, path) => `href="/${path}"`);
  return replaceLogoPlaceholders(fixedHrefHtml, brief);
}

async function saveSnapshotForJob(snapshot: ProjectSnapshot, userId: string): Promise<ProjectSnapshot> {
  return saveProjectSnapshot(snapshot, userId, { admin: true });
}

function cloneSnapshotWithProject(snapshot: ProjectSnapshot, project: Project): ProjectSnapshot {
  return {
    project,
    editorState: snapshot.editorState,
    aiChats: snapshot.aiChats,
  };
}

async function buildBlueprintStep(snapshot: ProjectSnapshot, job: ProjectGenerationJob, workerId: string) {
  await consumeAIUsageCredits(job.userId, "blueprint", { admin: true });

  const blueprint = await generateBlueprint(snapshot.project.brief);
  const pendingPages = buildPendingPages(blueprint);
  const now = new Date().toISOString();
  const nextProject: Project = {
    ...snapshot.project,
    brief: snapshot.project.brief,
    blueprint,
    files: buildInitialFiles(blueprint),
    pages: pendingPages,
    status: pendingPages.length > 0 ? "generating" : "ready",
    updatedAt: now,
  };

  const savedSnapshot = await saveSnapshotForJob(cloneSnapshotWithProject(snapshot, nextProject), job.userId);

  if (savedSnapshot.project.pages.length === 0) {
    const completedJob = await completeGenerationJob(job.id, "Your website is ready!", { admin: true });
    return {
      job: completedJob,
      shouldContinue: false,
    };
  }

  const nextPage = savedSnapshot.project.pages[0];
  const updatedJob = await updateGenerationJob(
    job.id,
    {
      status: "running",
      lockedBy: workerId,
      lockedAt: now,
      heartbeatAt: now,
      startedAt: job.startedAt ?? now,
      totalPages: savedSnapshot.project.pages.length,
      completedPages: 0,
      progressMessage: `Generating ${nextPage.name} (1/${savedSnapshot.project.pages.length})...`,
      currentPageId: nextPage.id,
      currentPageName: nextPage.name,
      lastError: null,
      lastErrorCode: null,
    },
    { admin: true }
  );

  return {
    job: updatedJob,
    shouldContinue: true,
  };
}

export async function runProjectGenerationJobStep(
  jobId: string,
  workerId: string
): Promise<ProjectGenerationStepResult> {
  const job = await getGenerationJobById(jobId, { admin: true });
  if (!job) {
    throw createAppError({
      code: DB_READ_002,
      devMessage: `Generation job ${jobId} was not found`,
      severity: "error",
      metadata: { jobId, workerId },
    });
  }

  if (job.status === "completed" || job.status === "failed" || job.status === "canceled") {
    return { job, shouldContinue: false };
  }

  if (job.lockedBy && job.lockedBy !== workerId) {
    throw createAppError({
      code: AUTH_PERMISSION_001,
      devMessage: `Worker ${workerId} attempted to process job ${jobId} locked by ${job.lockedBy}`,
      severity: "warn",
      metadata: { jobId, workerId, lockedBy: job.lockedBy },
    });
  }

  const runningJob = await touchGenerationJob(job.id, workerId, { admin: true });
  const snapshot = await getProjectSnapshot(runningJob.projectId, runningJob.userId, { admin: true });
  if (!snapshot) {
    const failed = await failGenerationJob(job.id, "The project could not be loaded for generation.", DB_READ_002, {
      admin: true,
    });
    return {
      job: failed,
      shouldContinue: false,
    };
  }

  try {
    if (!snapshot.project.blueprint) {
      return await buildBlueprintStep(snapshot, runningJob, workerId);
    }

    const pendingOrGenerating = snapshot.project.pages.find((page) => page.status === "pending" || page.status === "generating") ?? null;
    if (!pendingOrGenerating) {
      const readyProject: Project = {
        ...snapshot.project,
        status: "ready",
        updatedAt: new Date().toISOString(),
      };
      await saveSnapshotForJob(cloneSnapshotWithProject(snapshot, readyProject), runningJob.userId);
      const completedJob = await completeGenerationJob(runningJob.id, "Your website is ready!", { admin: true });
      return {
        job: completedJob,
        shouldContinue: false,
      };
    }

    const totalPages = snapshot.project.pages.length;
    const currentIndex = snapshot.project.pages.findIndex((page) => page.id === pendingOrGenerating.id);
    const displayIndex = currentIndex >= 0 ? currentIndex + 1 : snapshot.project.pages.filter((page) => page.status === "done").length + 1;
    const progressMessage = `Generating ${pendingOrGenerating.name} (${displayIndex}/${totalPages})...`;
    await updateGenerationJob(
      runningJob.id,
      {
        status: "running",
        progressMessage,
        totalPages,
        completedPages: snapshot.project.pages.filter((page) => page.status === "done").length,
        currentPageId: pendingOrGenerating.id,
        currentPageName: pendingOrGenerating.name,
      },
      { admin: true }
    );

    const generatingPages = snapshot.project.pages.map((page) =>
      page.id === pendingOrGenerating.id
        ? { ...page, status: "generating" as const, error: undefined }
        : page
    );
    const generatingProject: Project = {
      ...snapshot.project,
      pages: generatingPages,
      status: "generating",
      updatedAt: new Date().toISOString(),
    };
    await saveSnapshotForJob(cloneSnapshotWithProject(snapshot, generatingProject), runningJob.userId);

    await consumeAIUsageCredits(runningJob.userId, "generate-page", { admin: true });

    const persistedSnapshot = await getProjectSnapshot(runningJob.projectId, runningJob.userId, { admin: true });
    if (!persistedSnapshot?.project.blueprint) {
      throw createAppError({
        code: API_GENERATE_001,
        devMessage: `Blueprint disappeared before page generation for job ${runningJob.id}`,
        severity: "error",
        metadata: { jobId: runningJob.id, projectId: runningJob.projectId },
      });
    }

    const blueprintPage = resolveBlueprintPage(persistedSnapshot.project, pendingOrGenerating);
    const sharedNavbarHtml =
      currentIndex > 0
        ? extractNavbarHtml(persistedSnapshot.project.pages[0]?.html || "")
        : null;

    const result = await generatePage(
      persistedSnapshot.project.blueprint,
      blueprintPage,
      persistedSnapshot.project.brief,
      undefined,
      sharedNavbarHtml,
      null
    );

    const finalHtml = normalizeGeneratedHtml(result.html, persistedSnapshot.project.brief);
    const completedPages = persistedSnapshot.project.pages.map((page) =>
      page.id === pendingOrGenerating.id
        ? {
            ...page,
            html: finalHtml,
            sections: result.sections,
            status: "done" as const,
            error: undefined,
          }
        : page
    );

    const doneCount = completedPages.filter((page) => page.status === "done").length;
    const nextPending = completedPages.find((page) => page.status === "pending" || page.status === "generating") ?? null;
    const completedProject: Project = {
      ...persistedSnapshot.project,
      pages: completedPages,
      status: nextPending ? "generating" : "ready",
      updatedAt: new Date().toISOString(),
    };
    await saveSnapshotForJob(cloneSnapshotWithProject(persistedSnapshot, completedProject), runningJob.userId);

    if (!nextPending) {
      const completedJob = await completeGenerationJob(runningJob.id, "Your website is ready!", { admin: true });
      return {
        job: completedJob,
        shouldContinue: false,
      };
    }

    const nextIndex = completedPages.findIndex((page) => page.id === nextPending.id);
    const updatedJob = await updateGenerationJob(
      runningJob.id,
      {
        progressMessage: `Generating ${nextPending.name} (${nextIndex + 1}/${totalPages})...`,
        currentPageId: nextPending.id,
        currentPageName: nextPending.name,
        completedPages: doneCount,
        totalPages,
        heartbeatAt: new Date().toISOString(),
      },
      { admin: true }
    );

    return {
      job: updatedJob,
      shouldContinue: true,
    };
  } catch (error) {
    const appError = normalizeError(error, API_GENERATE_001, {
      jobId: runningJob.id,
      projectId: runningJob.projectId,
      workerId,
    });

    try {
      const latestSnapshot = await getProjectSnapshot(runningJob.projectId, runningJob.userId, { admin: true });
      if (latestSnapshot) {
        const currentPageId = runningJob.currentPageId;
        const nextPages = latestSnapshot.project.pages.map((page) =>
          currentPageId && page.id === currentPageId
            ? {
                ...page,
                status: "error" as const,
                error: appError.userMessage,
              }
            : page
        );

        const failedProject: Project = {
          ...latestSnapshot.project,
          pages: nextPages,
          status: "error",
          updatedAt: new Date().toISOString(),
        };

        await saveSnapshotForJob(cloneSnapshotWithProject(latestSnapshot, failedProject), runningJob.userId);
      }
    } catch {}

    const failedJob = await failGenerationJob(runningJob.id, appError.userMessage, appError.code, {
      admin: true,
    });

    return {
      job: failedJob,
      shouldContinue: false,
    };
  }
}
